services:
  - type: web
    name: pdf-tally-converter-api
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y tesseract-ocr libgl1-mesa-glx libglib2.0-0
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true 